individuals.json

I'm currently working for Google on Web standards.

Remove myself from the list of individuals

---

individuals.json

@annevk Please check it and verify.

Updated My Github ID (Aaqa Ishtyaq)

---

individuals.json

I'm no longer working at Google.
This reverts commit 3e3fcf5d4de3d5bf4e03e74851cf040a42f38f1b.

Revert "Remove myself from the list of individuals"

---

individuals.json

I am once again in @google organization.
This reverts commit 746cbda5fa701b3ab6905e20655712c660457b30.

Revert "Revert "Remove myself from the list of individuals""

---

individuals.json

Fixes [sg/101](https://github.com/whatwg/sg/issues/101)

Fix name @Rondinelly

---

individuals.json

Reverts whatwg/participant-data#12.
----
This is getting a bit tiring…

Revert "Revert "Revert "Remove myself from the list of individuals"""

---

individuals.json

I erroneously added myself as individual. Instead, I should have been added as part of an entity

removing myself as individual contributor

---

entities.json

With @michaelchampion's retirement, we are updating the Microsoft contact information for our WHATWG entity status. I will be the primary contact, and @jatindersmann, a Principle Group Program Manager in charge of product development on the HTML Platform team will fill the second contact spot.

Update Microsoft Entity contact info

---

entities.json

Shruthi has sadly moved on from Chrome, so we need new contacts for Google.
@henceproved, can you review/approve this pull request? Also @foolip since I'm adding you?
(As a matter of policy, it wouldn't be OK to merge this without @henceproved's approval, but I think it should be OK for me to send it and her to approve it.)

Update contacts for Google

---

individuals.json

This was for testing of https://github.com/whatwg/misc-server/pull/133.
This reverts commit f5b8a43b849ea579fc6599e200c773309b9ad494.

Revert "Add data for Tester Testsson"

---

individuals.json

This is Prosody's preferred form, per https://github.com/whatwg/sg/issues/101#issuecomment-662081615.

Update @payingattention's name

---

individuals.json

Per https://github.com/whatwg/sg/issues/101#issuecomment-661958660.

Unverify Yay295 and Osint Opsec

---

entities.json

Verify Keio University

---

entities.json

Remove mistaken Google entry

---

individuals.json

Mistyped my username

---

entities.json

Adding a second contact for F5 (Shape Security).

Update F5 (Shape Security) contacts

---

entities.json

Also update contact and address information.

Mozilla joins the Test Utils and Web IDL Workstreams

---

entities.json

PTAL @annevk 
Per https://participate.whatwg.org/agreement-update

Add Web IDL workstream for Intel Corporation

---

entities.json

Apple's joined the Web IDL Workstream.

---

entities.json

Hi!  Updating the Akamai contact information here.
Wasn't sure if anything else should be updated, e.g. `signature: {}` area?

Update Akamai contact

---

individuals.json

typo from entering form on my phone

Fix typo in my username

---

entities.json

change Mozilla contact2 to hsivonen

Mozilla contact2 hsivonen

---

individuals.json

Closes #55
Now affiliated with Apple.

Remove Marcos Cáceres as individual

---

entities.json

This follow https://github.com/whatwg/sg/pull/191.

Update secondary contact for Google

---

individuals.json

I now work at Igalia. Fixes https://github.com/whatwg/sg/issues/197.

Remove Nicolò Ribaudo from individuals.json

---

entities.json

Remove Noam Rosenthal

---

individuals.json

Vincent should be covered by Mozilla's org membership.

Remove Vincent Hilla from individuals.json

---

individuals.json

Hi :wave: 
I raised this PR to verify myself, to get https://github.com/whatwg/html/pull/9195 passing. Hopefully me filing this PR with my GPG signature acts as another vector for verification.

Remove Keith Cirkel (now part of MicrosoftWHATWGContributors)

---

individuals.json

I now work for Mozilla as of October 1st (cc @zcorpan)
(Also was invalid to use alias as an individual anyway, oops)

Remove @CanadaHonk from individuals.json

---

individuals.json

I have updated my participation to go through my company, through which I am paid to contribute to the [Servo project](https://github.com/servo/servo). 
See https://github.com/whatwg/participant-data/blob/16e741d5f7a85aaa9f673a56fe3672e037e2b2ac/entities.json#L1714

Remove Gregory Terzian from individuals.json

---

individuals.json

Removing myself from individuals as I'm employed by Fastly.

Remove Guy Bedford from individuals

---

entities.json

@guybedford noticed that our listed contacts no longer work at Fastly, I've volunteered to be the new Primary Contact for Fastly, please let me know if there are other actions I need to take for this to be accepted

Update Fastly contacts in entities.json

---

individuals.json

I recently changed my github username, this updates the participant data accordingly.

Update github username for Simon Wülker

---

individuals.json

Removing myself from individuals.json since I'm employed by Microsoft.

Remove Siye Liu from individuals.json

---

entities.json

Adds the storage workstream to Microsoft.

Includes storage to the MS workstream

---

individuals.json

Interested in contributing again.

Update data for Donovan Glover
